### ISSUE TITLE
Examples of evolving higher order functions and functions with multiple arguments?

### ISSUE THREAD

**Issue by wdkrnls** [fnoorian/gramEvol#10]
Hi! Very cool package! I had a question about whether it has support for higher order functions.

I often want to explore models using higher order functions like Box Cox transformations on parts of the feature space. So I write the higher order function `bcox` as below. Is it possible to encode these expressions into the grammar? e.g. so I could fit `y ~ bcox(0.2)(x1) + bcox(-0.5)(x2)` or more generally ` y ~ bcox(0.2)(x2 + 3*log(x1)) + bcox(-0.5 + exp(x1/5))(x2)`. I'm curious how I could represent that.

```
bcox = function(lambda, offset = 0) {
  function(x) {
    ((x + offset)^lambda - 1)/lambda
  }
}
```

**Comment by wdkrnls** [comment]
Reading the documentation more closely, I think this should be no problem for this library. I'll see if I can get it work.

**Comment by fnoorian** [comment]
Great!

By the way, all pull-requests for improving code functionality and document readability are more than welcome.

**Comment by fnoorian** [comment]
PS: You can also use `gvrule` and `gsrule` to simplify generating rules:

```
hyp = gvrule(1:5)
```

See vignette page on `gvrule` [here](https://fnoorian.github.io/gramEvol/inst/doc/ge-intro.html#using-vectors-as-rules).
