### ISSUE TITLE
Is there an easy way to use third party optimization libraries?

### ISSUE THREAD

**Issue by mytarmail** [fnoorian/gramEvol#12]
I would like to try other optimization packages, is there an easy way to do this?

**Comment by fnoorian** [comment]
Please explain what you want to do with other optimization packages. 

If you want to use another evolutionary algorithm to optimize within a grammar space, you can use this package's `GrammarMap` to convert a numeric vector to an expression (see [this guide](https://fnoorian.github.io/gramEvol/inst/doc/ge-intro.html#manual-mapping)). You only need to write enough boiler plate code to evaluate that expression in your cost function.

**Comment by mytarmail** [comment]
Hi Farzad!
Excuse me for my not very clear question

`Please explain what you want to do with other optimization packages.`

I just want to experiment with different optimization algorithms (multiobjective optimization for example) or even neural networks.

`If you want to use another evolutionary algorithm to optimize within a grammar space, you can use this package's GrammarMap to convert a numeric vector to an expression (see this guide). You only need to write enough boiler plate code to evaluate that expression in your cost function.
`

I have a few questions about `GrammarMap`

start code:
```
library(gramEvol)
grammarDef <- CreateGrammar(list(
  expr = gsrule("(<expr>)<op>(<expr>)", "<coef>*<var>"),
  op   = gsrule("+", "-", "*", "/"),
  coef = gsrule("c1", "c2"),
  var  = gsrule("v1", "v2")))

gen <- c(0, 1, 0, 0, 1, 1, 0, 0)
GrammarMap(gen, grammarDef)

(c1 * v1) - (c1 * v1) 
```

Now my questions:
1) How do I figure out what `length(gen)` a gene should be to cover all variants ?
```
gen <- c(0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1)
gen <- c(0, 1, 0, 0, 1, 1, 0, 0)
gen <- c(0, 1, 0, 0, 1)
```

2)   How do I figure out what should be the range of values in the gene
```
gen <- c(5, 1, 8, 0, 1, 12, 0, 0, 3, 0, 1, 0, 1)
```


I suspect that the vignette contains answers to these questions, but I want to be sure that I understood everything correctly.
Thanks you.
