### ISSUE TITLE
can i use continuous optimization in gramEvol

### ISSUE THREAD

**Issue by mytarmail** [fnoorian/gramEvol#16]
As I understand it, the package only uses discrete (binary) optimization with integer values ...

I have a question - would it be very wrong to use an algorithm with continuous optimization, and the output of the algorithm would simply be converted to an integer form

```
out_real_val <- runif(20,1,5)
> out_real_val
 [1] 4.258845 4.062256 4.318080 1.446091 1.696332 3.841191 2.379701 1.795424
 [9] 1.815174 3.017192 2.872621 4.239992 1.847689 2.986606 1.420673 3.995540
[17] 4.822753 2.358454 4.808910 3.152754
```

convert for `GrammarMap`

```
to_bin_val <- round(out_real_val,0)
> to_bin_val
 [1] 4 4 4 1 2 4 2 2 2 3 3 4 2 3 1 4 5 2 5 3
```
I wonder if I can do this or not, and if not, why?
thanks.

**Comment by fnoorian** [comment]
This really depends on what is the end goal, and how does the [fitness landscape](https://en.wikipedia.org/wiki/Fitness_landscape) look like.
This package follows the original GE design by O'Neill et al (see his website here http://www.grammatical-evolution.org/), which is discrete in nature. See their website for applications. This approach is inefficient for continuous variables.
If you have continuous variables, probably a general purpose continuous solver will help you reach your optima faster. See https://cran.r-project.org/web/views/Optimization.html for R packages. Based on your problem, you can pose it as a linear program or quadratic program, that can be solved efficiently. Or even it may turn out to have an analytical solution (by solving the dy/dx = 0).
If you are doing a classic machine learning classification/regression, it might be better to use tools developed in those areas (random forests, support vector machines, deep learning, etc).
If you want to do feature engineering (that is, creating new feature as inputs to your classifier/regressor), you might want to have a look at some hybrid methods (e.g. create features using grammar, give it to a linear regression, and evolve to minimize your learning error). See this book by De Silva et al. (who co-authored this R package) https://www.springer.com/gp/book/9789812874108 Code in that book is slightly out of date, but it gives you some ideas on what is a hybrid approach.

**Comment by mytarmail** [comment]
Thank you very much for your answer.
