### ISSUE TITLE
Bias in ga.new.chromosome

### ISSUE THREAD

**Issue by BeckerMatthias** [fnoorian/gramEvol#17]
Greetings,

I have been looking for a Genetic Algorithm that uses integers for R and have found your package incredibly helpful.
When reviewing the code, I noticed that the ga.new.chromosome function introduces a bias away from the values of genomeMin and genomeMax.

This is the code in use:

```
ga.new.chromosome <- function(genomeLen, genomeMin, genomeMax, allowrepeat) {
  chromosome = round(runif(genomeLen) * (genomeMax - genomeMin) + genomeMin)
  
  if (!allowrepeat) {
    chromosome = ga.unique.maker(chromosome, genomeMin, genomeMax)
  }
  
  return (chromosome)
}
```

Due to usage of the round function, the probability of a random value becoming genomeMin or genomeMax is halved.
This effect can be visualized like so:

```
genomeLen = 400
genomeMin = 1
genomeMax = 18
hist(round(runif(genomeLen ) * (genomeMax - genomeMin ) + genomeMin ), xlim=c(0,20), breaks = c(-0.5:19.5), col="gray")
```

A potential solution is to use a floor function instead, while widening the range of possible numbers auch as

`chromosome = floor(runif(genomeLen) * (genomeMax - (genomeMin - 1) ) + genomeMin)`

In the same scenario as before we now get an even distribution.

```
genomeLen = 400
genomeMin = 1
genomeMax = 18
hist(floor(runif(genomeLen ) * (genomeMax - (genomeMin  - 1) ) + genomeMin ), xlim=c(0,20), breaks = c(-0.5:19.5), col="gray")
```
Note that "runif will not generate either of the extreme values unless max = min or max-min is small compared to min, 
and in particular not for the default arguments." according to the documentation, so generating a value higher than genomeMax by chance will not occurr.

I am unsure how important this bias is generally and whether it may even be intended, but for the way I am applying this genetic algorithm I changed it and I thought I would bring it up to you.

Best wishes,
Matthias Becker

**Comment by fnoorian** [comment]
Thanks Matthias! This was an interesting yet unintended bias.
I have made the changes you suggested to the master branch.

Regards,
Farzad
