### ISSUE TITLE
How to get a sequence from an expression

### ISSUE THREAD

**Issue by mytarmail** [fnoorian/gramEvol#18]
```
library(gramEvol)
ruleDef <- list(expr =  gsrule("<var><op><var>"),
                op   =  gsrule("+", "-", "*"),
                var  =  grule(A, B, C))
grammarDef <- CreateGrammar(ruleDef)
```
I can get an expression from a sequence using the `GrammarMap` function
 ```
sq <- c(0, 0, 1, 2)
 expr <- GrammarMap(sq, grammarDef, verbose = F)
```

```
print(expr)
A - C 
```
How do I do the opposite, get a sequence using an expression. An expression is a regular string.
Have
`expr <- "A - C"`
I want to get seq
`c( 0 0 1 2)`

**Comment by fnoorian** [comment]
`gramEvol` doesn't support such functionality. What you need is a lexer or a parser that support BNF. I did a quick search and I found some R packages such as `rly` or `minilexer`, but I haven't worked with them myself. Also their syntax is a bit different from `gramEvols`.
