### ISSUE TITLE
Precedence over simpler expression with the same precision

### ISSUE THREAD

**Issue by mytarmail** [fnoorian/gramEvol#20]
Is there a precedence for the shorter expression?
For example, you need to find the number `"4"`

this can be done in many ways, for example
`1+1+1+1` or `3+1` or `2+2`
`2+2` is better than `1+1+1+1` because it's shorter.
Is there a built-in such search priority, if not, is it possible to do this?
Thank you!

**Comment by fnoorian** [comment]
At the moment we don't have anything built-in to do this, but I think it wouldn't be hard to implement it. One way I can think of it is to use something like `len(deparse(expr))` in the cost function. There, this can be directly added to the fitness of the expression (or alternatively, with some kind of weighting).

**Comment by mytarmail** [comment]
Thanks, it's hopeful
