### ISSUE TITLE
mutationChance argument in GeneticAlg.Int() function not working

### ISSUE THREAD

**Issue by marcabeer** [fnoorian/gramEvol#23]
It appears that the mutationChance argument in GeneticAlg.Int() does not work.

Borrowing the example code under the function's help information and modifying the mutationChance reveals this issue.

Code below for convenience:

evalfunc <- function(l) {
  odd <- seq(1, 20, 2)
  even <- seq(2, 20, 2)
  err <- sum(l[even]) - sum(l[odd]);
  
  stopifnot(!any(duplicated(l))) # no duplication allowed
  
  return (err)
}

monitorFunc <- function(result) {
  cat("Best of gen: ", min(result$best$cost), "\n")
}

x <- GeneticAlg.int(genomeLen = 20, codonMin = 0, codonMax = 20,
                    allowrepeat = FALSE, terminationCost = -110, mutationChance=0.25,
                    monitorFunc = monitorFunc, evalFunc = evalfunc, verbose=TRUE)

**Comment by fnoorian** [comment]
Closing as PR #24 is merged now. Feel free to re-open if the new message doesn't make sense.
