### ISSUE TITLE
start searching for the optimal solution from the expression I specified

### ISSUE THREAD

**Issue by mytarmail** [fnoorian/gramEvol#25]
I have a huge grammar and I would like to reduce the lookup by giving my initial expression.
for example
```
library(gramEvol)
ruleDef <- list(
exp = grule(op(var,var) , op(var,exp) , op(exp,exp)),
var = grule(a,b,c,e,f), 
op = grule("+","-","/","*"))

grammarDef <- CreateGrammar(ruleDef)
GrammarRandomExpression(grammarDef, 5)

[[1]]
expression(c/(b + e * (c - c)))

[[2]]
expression(f * f + (c + f/e) + (f + b))

[[3]]
expression(e + e * b)
```

For example - can I start searching with this expression?
`my_start_expr <- "f * f + (c + f/e) + (f + b)"`
Of course I don't know the `gene` of this expression, I can only express it as a string

The question is, can I run the search algorithm with my own expression string?

**Comment by fnoorian** [comment]
To do this, we will need a BNF parser to parse the expression against the given grammar. In theory this is easy (usually an undergraduate level homework), but as it was originally out of scope we never added it to the package. Unfortunately I don't have enough free time to add it now.

**Comment by mytarmail** [comment]
So sad(

**Comment by mytarmail** [comment]
Hello! Tell me please, is there a chance that a BNF parser will appear in the package?
