### ISSUE TITLE
how to freeze part of an expression for several other expressions

### ISSUE THREAD

**Issue by mytarmail** [fnoorian/gramEvol#29]
I want to implement indexing for multiple expressions like this
`X[ (i-n):i ],  X[ (i-n):i ]`
expressions should look like this
```
X[ (5-7):5 ],    X[ (5-7):5 ]

X[ (15-2):15 ],    X[ (15-2):15 ]
```

Here is what I have at the moment
```
library(gramEvol)
ruleDef <- list(
  xx = grule(c(x,x)),
  x  = gsrule("X[<ii>]"),
  
  ii = gsrule("(<i>-<n>):<i>"),                        
  i  = gvrule(1:20),
  n  = gvrule(1:100)
)
grammarDef <- CreateGrammar(ruleDef)
GrammarRandomExpression(grammarDef)

expression(c(X[(1 - 78):19], X[(15 - 34):2]))
```
I suspect the solution is very simple, maybe I just need coffee, but I can't think of anything.

**Comment by fnoorian** [comment]
You can write a full function in a `grule`, so try defining two variables that take the dynamic value from the rest of the grammar and reuse them in your expression.

Example:
```R
library(gramEvol)

ruleDef <- list(
  xx = grule(function() {s = i - n; e = i; c(X[s:e], Y[s:e])}()),
  i  = gvrule(1:20),
  n  = gvrule(1:100)
)
grammarDef <- CreateGrammar(ruleDef)
GrammarRandomExpression(grammarDef)
```

Which gives:
```
expression(function() {
    s = 16 - 51
    e = 14
    c(X[s:e], Y[s:e])
}())
```

**Comment by mytarmail** [comment]
Thank you very much, Unfortunately I couldn't find a solution myself.


Are *( )* needed at the end of the expression, or is it a typo?

xx = grule(function() {s = i - n; e = i; c(X[s:e], Y[s:e])}*( )*)

The expression works identically without *()* or am I missing something?

Sincerely, Taras


ср, 19 июл. 2023 г. в 06:13, Farzad Noorian ***@***.***>:

> You can write a full function in a grule, so try defining two variables
> that take the dynamic value from the rest of the grammar and reuse them in
> your expression.
>
> Example:
>
> library(gramEvol)
> ruleDef <- list(
>   xx = grule(function() {s = i - n; e = i; c(X[s:e], Y[s:e])}()),
>   i  = gvrule(1:20),
>   n  = gvrule(1:100)
> )grammarDef <- CreateGrammar(ruleDef)
> GrammarRandomExpression(grammarDef)
>
> Which gives:
>
> expression(function() {
>     s = 16 - 51
>     e = 14
>     c(X[s:e], Y[s:e])
> }())

**Comment by fnoorian** [comment]
The code above creates a function and immediately executes it.

Effectively:
```R
function() { x }()
```
is a fancy way of writing `x`.

**Comment by mytarmail** [comment]
> The code above creates a function and immediately executes it.
> 
> Effectively:
> 
> ```r
> function() { x }()
> ```
> 
> is a fancy way of writing `x`.

I'm sorry, but I still don't understand how ` ()` makes a function execute

here is simple example

```
fu <- function() print("i work") 
```
```
fu()
[1] "i work"
```




```
library(gramEvol)
ruleDef <- list(
              func = grule(function() print("i work") () )
               )
grammarDef <- CreateGrammar(ruleDef)
```
.
```
 GrammarRandomExpression(grammarDef) |> eval()
function() print("i work")()

```
I am not getting a string as result
`[1] "i work"`

**Comment by fnoorian** [comment]
My R is getting rusty...

Try:
```R
library(gramEvol)

ruleDef <- list(
  xx = grule({ e = i; s = e - n; c(X[s:e], Y[s:e])}),
  i  = gvrule(1:20),
  n  = gvrule(1:100)
)
grammarDef <- CreateGrammar(ruleDef)
GrammarRandomExpression(grammarDef)
```

**Comment by mytarmail** [comment]
> My R is getting rusty...

my brain too ))

I made a reproducible example, maybe it will be useful for someone

```
X <- 1:1000
Y <- 1:1000

library(gramEvol)
ruleDef <- list(
  xx = grule({ e = i; s = e + n; c(X[s:e], Y[s:e]) }),
  i  = gvrule(1:20),
  n  = gvrule(1:100)
)
ruleDef |> CreateGrammar() |> GrammarRandomExpression() |> eval()
```
