### ISSUE TITLE
return a pair

### ISSUE THREAD

**Issue by nestordemeure** [fnoorian/gramEvol#4]
Is it possible to use a pair of expressions as the root in the expression tree? Something like : 
```
grammarDef <- CreateGrammar(list(
  pair  = grule(couple(expr, expr)),
  expr = grule(op(expr, expr), func(expr), var),
  func = grule(sin, cos, log, sqrt),
  op    = grule(`+`, `-`, `*`), # define unary operators
  var   = grule(distance, distance^n, n),
  n      = gvrule(1:4) # this is shorthand for grule(1,2,3,4)
))
```

I tried using a `list(expr, expr)` and `c(expr,expr)` but both caused a crash (script eating all the memory). I also tried using a `couple(expr,expr,member)` function (that returns the expression indiced by member) but the program refused it because it relies on a closure.

**Comment by nestordemeure** [comment]
Nevermind, I believe I forgot something during my first try : I have no more memory problem.

(As an aside, congratulation on the library, it does a great job)

**Comment by fnoorian** [comment]
Great to hear it was resolved.

By the way, if there is something that doesn't sound clear in documentation or can benefit from an example, just send me a pull request.
