### ISSUE TITLE
factors in formula

### ISSUE THREAD

**Issue by csetzkorn** [fnoorian/gramEvol#6]
Thanks for creating this package. Just curious, do I have to create factors in formulas like this manually/explicitly using n in the grammar definition?

y = 10.3 + 2.3 * x

grammarDef <- CreateGrammar(list(
  expr  = grule(op(expr, expr), func(expr), var),
  func  = grule(exp),
  op    = grule(`+`, `-`, `*`), 
  var   = grule(x, n),
  n     = gvrule(10.3, 2.3 ) 
))

Hope this makes sense? Or could I say pick factors in a range from [-10 ... 10]?

**Comment by fnoorian** [comment]
So, do you want to make any `y=ax + b`?
As in:
```R
grammarDef <- CreateGrammar(list(
    expr = grule(f*x+f),
    f = gvrule(seq(-10, 10, 0.1))
))
```

**Comment by csetzkorn** [comment]
oh that's cool. One can basically also specify the formula and the range of parameter f. Can one define several parameters and their ranges (e.g. f1, f1) like so:

grammarDef <- CreateGrammar(list(
    expr = grule(f1*x+f2),
    f 1= gvrule(seq(-10, 10, 0.1)),
 f 2= gvrule(seq(-100, 10, 0.1234))
))

**Comment by fnoorian** [comment]
Yes. You can put any list inside a `gvrule`.

**Comment by csetzkorn** [comment]
Sorry one more question. How can I have terminal nodes, which are (random) numbers (or numbers between a min and max)? Above, we defined parameters f1 + f2 but how can "number terminal nodes" be allowed? I hope this makes sense? So the grammar allows two features x1 and x2 and formulas like this can be generated:

y = 3.12 * x1 + x1*x2 + 345.5 + x2*x2

**Comment by fnoorian** [comment]
It is not directly possible; mainly because in the current implementation, I am assuming that each chromosome is mapped to a unique expression. If we allow for random numbers, this uniqueness will be lost.

But you still can have random numbers in your grammar:
```R
grammarDef <- CreateGrammar(list(
    expr = grule({
                  a <- f;
                  b <- f;
                  a*x+b}),
    f = grule(runif(1,0, 10))
))
```

**Comment by csetzkorn** [comment]
Sorry I hope there is no misunderstanding. I did not mean random number literally but rather allow numbers to be used in the trees - as in standard genetic programming. Let us say we allow operators: + and *, trees like this could be created:

(3*x1) + (5*x2)

Here 3 and 5 are these number + and * are operators and x1 and x2 are features from the training data.

**Comment by fnoorian** [comment]
If we know these numbers beforehand, yes:

```R
grammarDef <- CreateGrammar(list(
    expr = grule(op(n*feat, n*feat)),
    feat = grule(x1, x2),
    op = grule(`+`, `-`, `*`),
    n = gvrule(c(1,2,3,4,5,6,7,8,9,10)),
))
```

If not, please specify your grammar in formal Backus-Naur form and we can work from there.

**Comment by vonGameTheory** [comment]
If you want to fill in values during evaluation, you can fill in a vector (array) of whatever data which is then referred to in your generated expressions.  So then you just have rules that give indexes instead of actual values, e.g.

 var = gsrule("v[<index>]"),
index = gvrule(1:4) # this gives you indexes 1-4

So this would generate expressions with "v[1]" or "v[2]", etc

Then in your cost function, you'd define vector v before evaluating the given expression

v <- whatever_data_array_with_4_values # "v" is now assigned and expr can refer to its values
result <- eval(expr) 

And if needed, that could be in a loop if you want to evaluate different values from a dataset in vector v to calculate your fitness.

**Comment by csetzkorn** [comment]
Thanks. This makes sense and could be useful. However, I want evolution to find these values. These numbers would correspond to "evolved numbers", which are part of the terminal set in genetic programming. Surely this must be possible?

**Comment by fnoorian** [comment]
@csetzkorn,  can you give a reference or an example to "evolved numbers" in GP?

**Comment by csetzkorn** [comment]
This is the first tutorial on GP I found:

https://web.cs.ucdavis.edu/~vemuri/classes/ecs271/The%20GP%20Tutorial.htm

There are crossover examples. The trees contain the number 2 (example!) as terminal nodes. These numbers tend to be evolved. For example there will be a function to get a terminal node node. It may return a variable name of the dataset's features or a randomly generated number. The fitness of the number is determines when one executes the formula. Over time fitter numbers are accumulated via evolution. They are spread by crossover and new ones are introduced by mutation operations ... 

I also refer you of one of my many papers:

http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.153.1169&rep=rep1&type=pdf

The section "The representation scheme" may be relevant. 

I hope this makes sense?

**Comment by vonGameTheory** [comment]
If you are just looking for constants to fill in an existing formula, you don't really need symbolic regression since you have the expression already, and so just need regression or a basic GA to find a vector of valves. 

If you want to evolve the formula itself with the possibility of it having some unknown constants in it, then that can be achieved in a variety of ways.   I know GP variants do sometimes just have randomized constants as part of the gene.  That's what you are looking for?

**Comment by vonGameTheory** [comment]
I can show you at least a couple ways to approach that, but I must finish my coffee and do some real work now.  I'll play around with it later today.  Is there a specific problem/example you have in mind?

**Comment by csetzkorn** [comment]
Have you finished your coffee? Still waiting (-:

**Comment by vonGameTheory** [comment]
Sorry, got busy.  I did find this, which gives you the basic approaches:

https://cs.stackexchange.com/questions/60712/gramatical-evolution-doesnt-result-on-creating-good-constants/60783

**Comment by fnoorian** [comment]
@csetzkorn , have you seen this paper that comes with the package?

https://www.jstatsoft.org/article/view/v071i01

In Section 4.3, it does a linear regression from some randomly generated features to data, so you wouldn't need to specify any random weights or biases directly.

**Comment by csetzkorn** [comment]
Thanks for your feedback. Will digest ...
