### ISSUE TITLE
Invalid cost function return value (NA or NaN)

### ISSUE THREAD

**Issue by csetzkorn** [fnoorian/gramEvol#7]
I am getting:

Error in EvolutionStrategy.int(genomeLen = chromosomeLen, codonMin = 0,  : 
  Invalid cost function return value (NA or NaN).

So I adopted the cost function as follows:

SymRegFitFunc <- function(expr) {
    result <- eval(expr)
    if (any(is.nan(result)) || any(is.na(result)))
        return(Inf)
    return(mean(log(1 + abs(y - result))))
}

Still the same issue. Any idea? Thanks!

**Comment by fnoorian** [comment]
Can you send an example of such function?
For example, by adding a print to you cost function as follows
```R
SymRegFitFunc <- function(expr) {
    result <- eval(expr)
    print(result)
    print(expr)
    if (any(is.nan(result)) || any(is.na(result)))
        return(Inf)
    return(mean(log(1 + abs(y - result))))
}
```

**Comment by csetzkorn** [comment]
Please ignore me - I found the error!
