### ISSUE TITLE
Installation from github?

### ISSUE THREAD

**Issue by vonGameTheory** [fnoorian/gramEvol#9]
I was trying to get "suggestions" to work, but was getting an error.  Looks like you actually fixed that problem so I wanted to install the latest version from github using devtools, but that doesn't seem to work.   Says it is not a proper archive:

`
> devtools::install_github("fnoorian/gramEvol")
Downloading GitHub repo fnoorian/gramEvol@master
tar: This does not look like a tar archive

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
tar: This does not look like a tar archive

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Error in getrootdir(untar(src, list = TRUE)) : 
  length(file_list) > 0 is not TRUE
In addition: Warning messages:
1: In utils::untar(tarfile, ...) :
  ‘tar -xf '/tmp/RtmpDXZwtO/file1a724a1b5a3a.tar.gz' -C '/tmp/RtmpDXZwtO/remotes1a721b914521'’ returned error code 2
2: In system(cmd, intern = TRUE) :
  running command 'tar -tf '/tmp/RtmpDXZwtO/file1a724a1b5a3a.tar.gz'' had status 2
> `

**Comment by vonGameTheory** [comment]
I was able to build it by downloading the zip file and doing it manually, but I had to delete the "vignettes" folder as that was throwing errors.  Seems like the source is not quite completely prepared for building/install.

**Comment by fnoorian** [comment]
It is very odd. I'm pretty sure it was getting built correctly on my Windows machine.

I wonder if a Travis CI script could help catch the actual problem.
